# Generated by Django 5.2.8 on 2025-11-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('product_type', models.CharField(choices=[('CANDLE', 'Candle'), ('SOAP', 'Soap')], max_length=12)),
                ('description', models.TextField(blank=True)),
                ('scent', models.CharField(help_text='e.g. Lavender, Citrus', max_length=50)),
                ('burn_time_min', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_g', models.PositiveIntegerField(help_text='Net weight in grams')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
