# Generated by Django 4.2.24 on 2025-12-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_burn_time_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags, e.g. winter, woody, refillable', max_length=250),
        ),
    ]
