# Generated by Django 4.2.24 on 2025-12-04 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_image_url_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='burn_time_min',
        ),
    ]
